### ISSUE TITLE
 Unexpected input(s) 'note', valid inputs are ['api_key', 'site_id', 'url_id', 'replace_origin']

### ISSUE THREAD

**Issue by sethidden** [SpeedCurve-Metrics/speedcurve-test-action#68]
Hey, ran into an issue where I used the action as written in the docs, but the "note" parameter doesn't seem to be seen by GitHub? Is this an issue with the action deployment?

See https://github.com/vuestorefront/magento2/actions/runs/2172399318

<img width="768" alt="image" src="https://user-images.githubusercontent.com/5359825/163568973-33a162b1-dfa5-4ac3-be7f-7edfe9654c94.png">

The workflow file looks like this:
```yml
name: "Run SpeedCurve test"

on:
  # deployment_status:
  push:
    branches:
      - perf/speedcurve-integration-ci

jobs:
  speedcurve:
    # if: github.deployment.ref == 'refs/heads/develop' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      # - name: 'Wait for container deployed on VSF Cloud to come online'
      #   run: 'sleep 300'
      #   shell: 'bash'


      - name: 'Ask SpeedCurve to run performance tests'
        uses: SpeedCurve-Metrics/speedcurve-test-action@v1.2.1
        with:
          api_key: ${{ secrets.SPEEDCURVE_API_KEY }}
          site_id: 744017
          note: "commit ${{ github.deployment.sha }} from deployment ${{ github.deployment.url }}"

```
